---
- hosts: border
  gather_facts: yes
  tasks:
    - name: "ensure logging and ntp is configured"
      include_role:
        name: common

    - name: "setting up the broder switches with roles exit"
      include_role:
        name: exit

    - name: "configure link to firewall"
      nclu:
        commands:
          - add interface {{ external_interface_firewall }} ip address {{ external_firewall_ip }}/{{ external_firewall_sm }}
        commit: true

