---
# vars file for common
#
cumulususers:
  - cumulus
snmppass: snmp123
defaultntp:
  - 0.cumulusnetworks.pool.ntp.org
  - 1.cumulusnetworks.pool.ntp.org
  - 2.cumulusnetworks.pool.ntp.org
  - 3.cumulusnetworks.pool.ntp.org

ntpservers:
 - 0.home.ntp.org
 - 1.home.ntp.org
 - 2.home.ntp.org
 - 3.home.ntp.org

syslogservers:
  - 10.0.0.1
  - 10.0.0.2
  - 10.0.0.3
